// Generated by https://quicktype.io

export interface ResponsePokemon {
  count: number
  next: string
  previous: null
  results: Pokemon[]
}

export interface Pokemon {
  name: string
  url: string
}

// Detail Pokemon 🐈
export interface ResponseDetailPokemon {
  name: string
  height: number
  types: TypeElement[]
  weight: number
}

export interface TypeElement {
  slot: number
  type: TypeType
}

export interface TypeType {
  name: string
  url: string
}

export interface PokemonDetails {
  name: string
  weight: number
  type: string // Opcional: si solo necesitas el nombre del tipo
  height: number
}
